# Generated by Django 5.2.7 on 2025-11-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
