# Generated by Django 5.2.7 on 2025-11-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_alter_plan_options_usercredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercredit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
