# Generated by Django 5.2.7 on 2025-10-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userskill'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together=set(),
        ),
    ]
