# Generated by Django 5.2.7 on 2025-10-31 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexperience',
            name='currently_working',
            field=models.BooleanField(default=False),
        ),
    ]
