# Generated by Django 5.2.7 on 2025-11-05 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('llm_models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('proposal_generation', 'Proposal Generation'), ('resume', 'Resume'), ('cover_letter', 'Cover Letter'), ('other', 'Other')], max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='queued', max_length=20)),
                ('input', models.JSONField()),
                ('result_meta', models.JSONField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('llm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm_models.llm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('job_post', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('friendly', 'Friendly'), ('persuasive', 'Persuasive'), ('formal', 'Formal'), ('casual', 'Casual')], max_length=20)),
                ('generated_text', models.TextField()),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('public', 'Public')], default='private', max_length=10)),
                ('tokens_prompt', models.PositiveIntegerField(default=0)),
                ('tokens_completion', models.PositiveIntegerField(default=0)),
                ('tokens_total', models.PositiveIntegerField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposal', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proposals',
            },
        ),
        migrations.CreateModel(
            name='BillingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_prompt', models.PositiveIntegerField()),
                ('tokens_completion', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('llm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm_models.llm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.proposal')),
            ],
            options={
                'db_table': 'billing_logs',
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status'], name='jobs_status_92f544_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['user'], name='jobs_user_id_d36cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['user'], name='proposals_user_id_87b85c_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['visibility'], name='proposals_visibil_40065f_idx'),
        ),
        migrations.AddIndex(
            model_name='billinglog',
            index=models.Index(fields=['user'], name='billing_log_user_id_877aa4_idx'),
        ),
    ]
