# Generated by Django 5.2.7 on 2025-11-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='input',
            new_name='user_prompt',
        ),
    ]
