# Generated by Django 5.2.7 on 2025-11-05 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_input_job_user_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='job_post',
            new_name='prompt',
        ),
    ]
