# Generated by Django 5.2.7 on 2025-11-05 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_job_post_proposal_prompt'),
        ('llm_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='llm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='llm_models.llm'),
        ),
    ]
