# Generated by Django 5.2.7 on 2025-11-02 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_alter_usercredit_user'),
        ('subsctiptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsctiption',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsctiptions', to='credits.plan'),
        ),
    ]
