# Generated by Django 5.2.7 on 2025-11-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsctiptions', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('stripe', 'Stripe'), ('other', 'Other')], default='credit_card', max_length=50),
        ),
    ]
