# Generated by Django 5.2.7 on 2025-11-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subsctiptions', '0004_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
