# Generated by Django 5.2.7 on 2025-11-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llm',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='llm',
            name='api_endpoint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='llm',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('huggingface', 'HuggingFace'), ('gemini', 'Gemini'), ('claud', 'Claude'), ('custom', 'Custom')], max_length=255),
        ),
    ]
