# Generated by Django 5.2.7 on 2025-11-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_models', '0002_alter_llm_active_alter_llm_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llm',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('huggingface', 'HuggingFace'), ('gemini', 'Gemini'), ('anthropic', 'Anthropic'), ('custom', 'Custom')], max_length=255),
        ),
    ]
